### Merge, concat e join:

In [5]:
import pandas as pd
import numpy as np
from numpy.random import randn

In [87]:
df1 = pd.DataFrame({
    'A' : ['A0', 'A1', 'A2', 'A3'],
    'B' : ['B0', 'B1', 'B2', 'B3'],
    'C' : ['C0', 'C1', 'C2', 'C3'],
    'D' : ['D0', 'D1', 'D2', 'D3']
    },
    index=[0, 1, 2, 3])

In [88]:
df2 = pd.DataFrame({
    'A' : ['A4', 'A5', 'A6', 'A7'],
    'B' : ['B4', 'B5', 'B6', 'B7'],
    'C' : ['C4', 'C5', 'C6', 'C7'],
    'D' : ['D4', 'D5', 'D6', 'D7']
    },
    index=[4, 5, 6, 7])

In [89]:
df3 = pd.DataFrame({
    'A' : ['A8', 'A9', 'A10', 'A11'],
    'B' : ['B8', 'B9', 'B10', 'B11'],
    'C' : ['C8', 'C9', 'C10', 'C11'],
    'D' : ['D8', 'D9', 'D10', 'D11']
    },
    index=[8, 9, 10, 11])

In [90]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [91]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [92]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [93]:
# concat soma o conjunto de dados
# concat(), CONCATENAR
# junta na horiental
pd.concat([df1, df2, df3])
# é possível concatenar pelas colunas, pelo axis(0 = índice, 1 = coluna)
# só utiliza axis = 1 quando os conjuntos compartilham a msm coluna

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [94]:
esquerda = pd.DataFrame({
    'key' : ['K0', 'K1', 'K2', 'K3'],
    'A' : ['A0', 'A1', 'A2', 'A3'],
    'B' : ['B0', 'B1', 'B2', 'B3']})

In [95]:
direita = pd.DataFrame({
    'key' : ['K0', 'K1', 'K2', 'K3'],
    'A' : ['C0', 'C1', 'C2', 'C3'],
    'B' : ['D0', 'D1', 'D2', 'D3']})

In [96]:
esquerda

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [97]:
direita

  key   A   B
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [98]:
pd.merge(esquerda, direita, on='key')
# é utilizado para juntar, msm tendo uma coluna igual nas datas

  key A_x B_x A_y B_y
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [99]:
direita = pd.DataFrame({
    'key1' : ['K0', 'K0', 'K1', 'K2'],
    'key2' : ['K0', 'K1', 'K0', 'K1'],
    'A' : ['A0', 'A1', 'A2', 'A3'],
    'B' : ['B0', 'B1', 'B2', 'B3']})

In [100]:
esquerda = pd.DataFrame({
    'key1' : ['K0', 'K1', 'K1', 'K2'],
    'key2' : ['K0', 'K0', 'K0', 'K0'],
    'A' : ['A0', 'A1', 'C2', 'C3'],
    'B' : ['D0', 'D1', 'D2', 'D3']})

In [101]:
esquerda

  key1 key2   A   B
0   K0   K0  A0  D0
1   K1   K0  A1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [102]:
direita

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [103]:
pd.merge(esquerda, direita, on=['key1', 'key2'])
# procura ocorências dos pares que ocorrem de maneira simultânea na esquerda e na direita

  key1 key2 A_x B_x A_y B_y
0   K0   K0  A0  D0  A0  B0
1   K1   K0  A1  D1  A2  B2
2   K1   K0  C2  D2  A2  B2

In [104]:
pd.merge(esquerda, direita, how= 'left', on=['key1', 'key2']) # é possível inserir um argumento how, que mostra de maneiras diferentes
# procura ocorências dos pares que ocorrem de maneira simultânea na esquerda e na direita
# é baseado nas colunas

  key1 key2 A_x B_x  A_y  B_y
0   K0   K0  A0  D0   A0   B0
1   K1   K0  A1  D1   A2   B2
2   K1   K0  C2  D2   A2   B2
3   K2   K0  C3  D3  NaN  NaN

In [105]:
esquerda = pd.DataFrame({
    'A' : ['A0', 'A1', 'A2'],
    'B' : ['B0', 'B1', 'B2']},
    index= ['K0', 'K1', 'K2'])

In [106]:
direita = pd.DataFrame({
    'C' : ['C0', 'C2', 'C3'],
    'D' : ['D1', 'D2', 'D3']},
    index= ['K0', 'K2', 'K3'])

In [107]:
esquerda

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [108]:
direita

     C   D
K0  C0  D1
K2  C2  D2
K3  C3  D3

In [109]:
esquerda.join(direita)
# parece com merge, porém é voltado ao índice

     A   B    C    D
K0  A0  B0   C0   D1
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

### Operações com DataFrame:

In [110]:
df = pd.DataFrame({
    'col1' : [1, 2, 3, 4],
    'col2' : [444, 555, 666, 444],
    'col3' : ['abc', 'def', 'ghi', 'xyz']
})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [111]:
df.info()
# fala o tipo dos dados

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      str
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [112]:
df.memory_usage()
# fala a quantidade de memória utilizada, em cada parte

Index    132
col1      32
col2      32
col3      32
dtype: int64

In [113]:
df['col2'].unique()
# retorna os que são únicos, tipo conjunto

array([444, 555, 666])

In [114]:
df['col2'].nunique()
# fala a quantidade de únicos

3

In [115]:
df['col2'].value_counts()
# diz quantas vezes cada elemento se repete

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [116]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [117]:
def comp(x):
    return x ** 2 + 3

In [118]:
df['col1'].apply(comp)
# .appy é possível passar um função, porém é necessário conter apenas um input

0     4
1     7
2    12
3    19
Name: col1, dtype: int64

In [119]:
df['col1_calc'] = df['col1'].apply(comp)

In [120]:
df

   col1  col2 col3  col1_calc
0     1   444  abc          4
1     2   555  def          7
2     3   666  ghi         12
3     4   444  xyz         19

In [121]:
df['col1'].apply(lambda x: x**2 + 3)
# utilize lambda no apply, é uma def que só existe no instante do código

0     4
1     7
2    12
3    19
Name: col1, dtype: int64

In [122]:
df['col1'].sum()
# soma a Series

np.int64(10)

In [123]:
df['col1'].mean()
# faz a média da Series

np.float64(2.5)

In [124]:
df['col1'].product()
# multiplica a coluna

np.int64(24)

In [125]:
df['col1'].max()
# mostra o maior valor

np.int64(4)

In [126]:
df[df['col2'] == 444]

   col1  col2 col3  col1_calc
0     1   444  abc          4
3     4   444  xyz         19

In [127]:
df[df['col2'] == 444]['col1'].sum()
# é possível combinar com os filtros
# massa

np.int64(5)

In [128]:
df.sort_values(by='col2') 
# ordena de acordo com os valores, é necessário passar a coluna como referência

   col1  col2 col3  col1_calc
0     1   444  abc          4
3     4   444  xyz         19
1     2   555  def          7
2     3   666  ghi         12

In [129]:
data = {
    'A' : ['foo','foo', 'foo', 'bar', 'bar', 'bar'],
    'B' : ['one', 'one', 'two', 'two', 'one', 'one'],
    'C' : ['x', 'y', 'x', 'y', 'x', 'y'],
    'D' : [1, 3, 2, 5, 4, 1]
}
df = pd.DataFrame(data)

In [130]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [ ]:
dict_map = {
    'one' : 1,
    'two' : 2
}
# que legal, mapeia de acordo com o que aparece nas outras colunas

In [133]:
df['E'] = df['B'].map(dict_map)

In [134]:
df

     A    B  C  D  E
0  foo  one  x  1  1
1  foo  one  y  3  1
2  foo  two  x  2  2
3  bar  two  y  5  2
4  bar  one  x  4  1
5  bar  one  y  1  1

In [1]:
df.pivot_table(index= 'A', columns= 'B', values = 'D')
# é utilizado para criar uma tabela pivotada, se resume a uma nova forma de ordenar a linha de acordo com algo

NameError: name 'df' is not defined

### Serie temporal:

In [ ]:
# Serie temporal = é um conjunto de dados que em cada linha representa um momento diferente
# parece tranquilo de ser utilizado

In [3]:
numeros_de_dias = 100

In [ ]:
datas = pd.date_range(start='1/1/2021', periods= numeros_de_dias)
# cria um array com diversas datas, partindo do start

In [7]:
datas

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
               '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
               '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
               '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
               '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
               '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
               '2021-01-29', '2021-01-30', '2021-01-31', '2021-02-01',
               '2021-02-02', '2021-02-03', '2021-02-04', '2021-02-05',
               '2021-02-06', '2021-02-07', '2021-02-08', '2021-02-09',
               '2021-02-10', '2021-02-11', '2021-02-12', '2021-02-13',
               '2021-02-14', '2021-02-15', '2021-02-16', '2021-02-17',
               '2021-02-18', '2021-02-19', '2021-02-20', '2021-02-21',
               '2021-02-22', '2021-02-23', '2021-02-24', '2021-02-25',
               '2021-02-26', '2021-02-27', '2021-02-28', '2021-03-01',
               '2021-03-02', '2021-03-03', '2021-03-04', '2021-03-05',
               '2021-03-06', '2021-03-07', '2021-03-08', '2021-03-09',
               '2021-03-10', '2021-03-11', '2021-03-12', '2021-03-13',
               '2021-03-14', '2021-03-15', '2021-03-16', '2021-03-17',
               '2021-03-18', '2021-03-19', '2021-03-20', '2021-03-21',
               '2021-03-22', '2021-03-23', '2021-03-24', '2021-03-25',
               '2021-03-26', '2021-03-27', '2021-03-28', '2021-03-29',
               '2021-03-30', '2021-03-31', '2021-04-01', '2021-04-02',
               '2021-04-03', '2021-04-04', '2021-04-05', '2021-04-06',
               '2021-04-07', '2021-04-08', '2021-04-09', '2021-04-10'],
              dtype='datetime64[us]', freq='D')

In [8]:
df = pd.DataFrame(range(numeros_de_dias), columns=['number'], index=datas)

In [15]:
df

            number
2021-01-01       0
2021-01-02       1
2021-01-03       2
2021-01-04       3
2021-01-05       4
...            ...
2021-04-06      95
2021-04-07      96
2021-04-08      97
2021-04-09      98
2021-04-10      99

[100 rows x 1 columns]

In [16]:
df.index
# é um DateTime, python possui uma biblioteca DateTime

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
               '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
               '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
               '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
               '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
               '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
               '2021-01-29', '2021-01-30', '2021-01-31', '2021-02-01',
               '2021-02-02', '2021-02-03', '2021-02-04', '2021-02-05',
               '2021-02-06', '2021-02-07', '2021-02-08', '2021-02-09',
               '2021-02-10', '2021-02-11', '2021-02-12', '2021-02-13',
               '2021-02-14', '2021-02-15', '2021-02-16', '2021-02-17',
               '2021-02-18', '2021-02-19', '2021-02-20', '2021-02-21',
               '2021-02-22', '2021-02-23', '2021-02-24', '2021-02-25',
               '2021-02-26', '2021-02-27', '2021-02-28', '2021-03-01',
               '2021-03-02', '2021-03-03', '2021-03-04', '2021-03-05',
               '2021-03-06', '2021-03-07', '2021-03-08', '2021-03-09',
               '2021-03-10', '2021-03-11', '2021-03-12', '2021-03-13',
               '2021-03-14', '2021-03-15', '2021-03-16', '2021-03-17',
               '2021-03-18', '2021-03-19', '2021-03-20', '2021-03-21',
               '2021-03-22', '2021-03-23', '2021-03-24', '2021-03-25',
               '2021-03-26', '2021-03-27', '2021-03-28', '2021-03-29',
               '2021-03-30', '2021-03-31', '2021-04-01', '2021-04-02',
               '2021-04-03', '2021-04-04', '2021-04-05', '2021-04-06',
               '2021-04-07', '2021-04-08', '2021-04-09', '2021-04-10'],
              dtype='datetime64[us]', freq='D')

In [12]:
df.index[0].day

1

In [13]:
df.index[1].year

2021

In [14]:
df[df.index.day == 10]

            number
2021-01-10       9
2021-02-10      40
2021-03-10      68
2021-04-10      99

### Entrada e saída de dados

In [ ]:
# pandas IO é necessário pesquisar na documentação
# IO = input outpot
# .csv se comporta muito bem com o pandas
# leitura de dados é difícil, possui diversos parâmetros
# o segundo tipo de dados mais importante é o .csv(read_csv.(), to_csv())
# o mais importante é o SQl, read_sql() e to_sql()

In [ ]:
df1 = pd.read_csv('nomeArquivo', sep='(, ou ;)', decimal='(fala se é separado por . ou ,)')
# é necessário passar o nome do arquivo, ao botar dentro da pasta, deixando o jupyter no msm nível do arquivo

TypeError: read_csv() missing 1 required positional argument: 'filepath_or_buffer'

In [19]:
# após importar, é uma boa prática utilizar o .info(), para ver se deu tudo certo na conversão
# quando ver um conjunto de dados é melhor recorrer a documentação

In [ ]:
# é possível exportar o csv
df1.to_csv('exemplo.csv', sep =';', decimal=',')