### colunas = series,
### tabelas = dateframe

In [39]:
import pandas as pd
import numpy as np

COLUNAS:

In [40]:
labels = ['a', 'b', 'c']
minha_lista = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b':20, 'c': 30}

In [41]:
pd.Series(labels)
# faz um serie
# sempre dá índices

0    a
1    b
2    c
dtype: str

In [42]:
pd.Series(data = labels, index = minha_lista)
# é possível passar o que vai ser o índice

10    a
20    b
30    c
dtype: str

In [43]:
pd.Series(labels, minha_lista)

10    a
20    b
30    c
dtype: str

In [44]:
pd.Series(d)
# se já passar um dic deixa os índices = chaves, valores = valores
# pandas conversa muito bem com dicionários

a    10
b    20
c    30
dtype: int64

In [45]:
ser1 = pd.Series([1, 2, 3, 4], index = ['EUA', 'Alemanha', 'Rússia', 'Japão'])

In [46]:
ser1
# index é uma espécie de seletor, é um ponto central para a manipulação de dados

EUA         1
Alemanha    2
Rússia      3
Japão       4
dtype: int64

In [47]:
ser2 = pd.Series([1, 2, 5, 4], index = ['EUA', 'Alemanha', 'Italia', 'Japão'])

In [48]:
ser2

EUA         1
Alemanha    2
Italia      5
Japão       4
dtype: int64

In [ ]:
ser1[['EUA', 'Alemanha']]
# sae quiser pegar só um índice passe uma string
# se quiser pegar mais de um passe um array

EUA         1
Alemanha    2
dtype: int64

In [50]:
ser1 + ser2
# é possível fazer uma soma entre series, elas são orientadas pelo índice, se não aparecer nos dois arrays é retornado como valor NaN(not a number)

Alemanha    4.0
EUA         2.0
Italia      NaN
Japão       8.0
Rússia      NaN
dtype: float64

DATAFRAMES:

In [51]:
from numpy.random import randn
# numpy é uma biblioteca com algebra

In [ ]:
df = pd.DataFrame(randn(5, 4), index = ['A', 'B', 'C', 'D', 'E'], columns='W X Y Z'.split( ))
# cada valor é a composição de um índece com uma coluna
# coluna = parte de cima
# índice = parte lateral

In [57]:
df
# fica bem, mais organizado

          W         X         Y         Z
A  0.550799 -1.233541 -1.789317 -2.342879
B -0.607955  0.608923 -0.257519  1.096755
C  0.122623 -0.603464 -0.980661  0.990990
D -0.776677 -0.704831 -1.355560 -0.029366
E  0.024099  1.111668  0.115980  0.946532

In [59]:
type(df)

pandas.DataFrame

In [60]:
df['W']
# retorna um series
# diferente das series, é passado a coluna, não o índice
# dataframe = um conjunto de uma series

A    0.550799
B   -0.607955
C    0.122623
D   -0.776677
E    0.024099
Name: W, dtype: float64

In [61]:
df[['W']]
# devolver um dataframe
# indo contra o padrão de devolver em Series

          W
A  0.550799
B -0.607955
C  0.122623
D -0.776677
E  0.024099

In [ ]:
df['new'] = df['W']
# cria uma nova Serie com as informações da coluna W

In [63]:
df

          W         X         Y         Z       new
A  0.550799 -1.233541 -1.789317 -2.342879  0.550799
B -0.607955  0.608923 -0.257519  1.096755 -0.607955
C  0.122623 -0.603464 -0.980661  0.990990  0.122623
D -0.776677 -0.704831 -1.355560 -0.029366 -0.776677
E  0.024099  1.111668  0.115980  0.946532  0.024099

In [64]:
df['new2'] = df['W'] + df['Y']

In [65]:
df

          W         X         Y         Z       new      new2
A  0.550799 -1.233541 -1.789317 -2.342879  0.550799 -1.238518
B -0.607955  0.608923 -0.257519  1.096755 -0.607955 -0.865474
C  0.122623 -0.603464 -0.980661  0.990990  0.122623 -0.858038
D -0.776677 -0.704831 -1.355560 -0.029366 -0.776677 -2.132237
E  0.024099  1.111668  0.115980  0.946532  0.024099  0.140079

In [ ]:
del df['new']
# deleta uma Serie(coluna)

In [67]:
df

          W         X         Y         Z      new2
A  0.550799 -1.233541 -1.789317 -2.342879 -1.238518
B -0.607955  0.608923 -0.257519  1.096755 -0.865474
C  0.122623 -0.603464 -0.980661  0.990990 -0.858038
D -0.776677 -0.704831 -1.355560 -0.029366 -2.132237
E  0.024099  1.111668  0.115980  0.946532  0.140079

In [ ]:
df.drop('new2', axis= 1)
# axis = 1 = colunas
# axis = 0 = linhas
# retorna um novo dataframe, n modifica o original, caso n modifique o inplace, que é por padrão False

          W         X         Y         Z
A  0.550799 -1.233541 -1.789317 -2.342879
B -0.607955  0.608923 -0.257519  1.096755
C  0.122623 -0.603464 -0.980661  0.990990
D -0.776677 -0.704831 -1.355560 -0.029366
E  0.024099  1.111668  0.115980  0.946532

In [72]:
df.drop('new2', axis= 1, inplace=True)
# inplace = True , altera o dataframe original, várias funções em pandas contém essa funcionalidade

In [73]:
df

          W         X         Y         Z
A  0.550799 -1.233541 -1.789317 -2.342879
B -0.607955  0.608923 -0.257519  1.096755
C  0.122623 -0.603464 -0.980661  0.990990
D -0.776677 -0.704831 -1.355560 -0.029366
E  0.024099  1.111668  0.115980  0.946532

In [74]:
df.loc['A']
# igual as outras funções da biblioteca pandas se passar o argumento em um array é possível ver mais de uma info
# se passar um array retorna um DataFrame
# loc, procura um A nas linhas
# devolve uma Series

W    0.550799
X   -1.233541
Y   -1.789317
Z   -2.342879
Name: A, dtype: float64

In [75]:
df.iloc[0,2]
# é um modo de pesquisar utilizandon os índices, 1 linha, dps coluna(series)

np.float64(-1.7893167441794453)