### Iloc e filtros:

In [5]:
import pandas as pd
import numpy as np
from numpy.random import randn

In [6]:
df = pd.DataFrame(randn(5, 4), index = ['A', 'B', 'C', 'D', 'E'], columns='W X Y Z'.split( ))

In [ ]:
df['W']
# pega a coluna do DataFrame
# retorna uma Series

A    0.722126
B    1.278790
C    2.397857
D   -2.061293
E    0.747019
Name: W, dtype: float64

In [9]:
df[['W', 'Y']]
# se botar uma lista pega mais de uma Series, retornando um DataFrame

          W         Y
A  0.722126 -0.495746
B  1.278790  0.648145
C  2.397857 -0.809873
D -2.061293 -0.753148
E  0.747019 -1.211252

In [11]:
df['W']
# ainda retorna um DataFrame, msm sendo só um elemento, pois está contido em um array

A    0.722126
B    1.278790
C    2.397857
D   -2.061293
E    0.747019
Name: W, dtype: float64

In [12]:
df.loc[['A', 'B']]
# pega pelo índice

          W         X         Y         Z
A  0.722126 -0.024349 -0.495746 -0.455249
B  1.278790  0.928622  0.648145 -0.137351

In [13]:
df.iloc[0, 2] 
# pega pela posição
# primeiro parâmetro = índice
# segundo parâmetro = coluna

np.float64(-0.49574649143819244)

In [15]:
df.loc[['A', 'B'], 'W'] 
# tem um segundo parâmetro opcional, que adiciona mais um filtro por coluna
# retorna uma Series
# se botar um Array retorna um DataFrame

A    0.722126
B    1.278790
Name: W, dtype: float64

In [ ]:
df.iloc[1:, :]
# : seleciona tudo, é possível limitar os dois pontos, caso seja posto um número ao lado
# 1 tira o primeiro elemento
# -1 tira o último eleemnto
# muito parecido com o slicing dos arrays

          W         X         Y         Z
B  1.278790  0.928622  0.648145 -0.137351
C  2.397857 -1.606492 -0.809873 -0.859328
D -2.061293 -0.770464 -0.753148  1.179107
E  0.747019  2.836140 -1.211252  0.727634

In [28]:
df.iloc[1:4, 1:3 ]
# retira linhas e colunas

          X         Y
B  0.928622  0.648145
C -1.606492 -0.809873
D -0.770464 -0.753148

In [30]:
df > 0
# muito legal, é bem simples utilizar as condicionais

       W      X      Y      Z
A   True  False  False  False
B   True   True   True  False
C   True  False  False  False
D  False  False  False   True
E   True   True  False   True

In [ ]:
df[df > 0]
# muito legal, poder passar na pesquisa uma condição

          W         X         Y         Z
A  0.722126       NaN       NaN       NaN
B  1.278790  0.928622  0.648145       NaN
C  2.397857       NaN       NaN       NaN
D       NaN       NaN       NaN  1.179107
E  0.747019  2.836140       NaN  0.727634

In [ ]:
df['Z'] > 0
# se for coluna retorna True os false

A    False
B    False
C    False
D     True
E     True
Name: Z, dtype: bool

In [35]:
df[df['W'] > 0]
# seleciona os dados da coluna W, retornando os positivo

          W         X         Y         Z
A  0.722126 -0.024349 -0.495746 -0.455249
B  1.278790  0.928622  0.648145 -0.137351
C  2.397857 -1.606492 -0.809873 -0.859328
E  0.747019  2.836140 -1.211252  0.727634

In [ ]:
df[(df['W'] > 0) & (df['Y'] > 0)]
# [] = quando
# se não botar entre () retorna um valor booleano

         W         X         Y         Z
B  1.27879  0.928622  0.648145 -0.137351

### Mais detalhes do índice:

In [ ]:
df.index
# retorna os índices do DataFrame

Index(['A', 'B', 'C', 'D', 'E'], dtype='str')

In [ ]:
df.columns
# retorna as colunas do DataFrame

Index(['W', 'X', 'Y', 'Z'], dtype='str')

In [42]:
df.reset_index(inplace=True)
# substitui os índices por um valor bem simples, começando no 0
# para fazer a alteração real é necessário botar inplace = True

In [43]:
df

  index         W         X         Y         Z
0     A  0.722126 -0.024349 -0.495746 -0.455249
1     B  1.278790  0.928622  0.648145 -0.137351
2     C  2.397857 -1.606492 -0.809873 -0.859328
3     D -2.061293 -0.770464 -0.753148  1.179107
4     E  0.747019  2.836140 -1.211252  0.727634

In [45]:
df.set_index('index', inplace=True)
# retira o index_reset

In [46]:
novoind = 'CA NY OR CO WY'.split()

In [ ]:
df['novo_index'] = novoind
# adiciona um novo_indice

In [48]:
df

              W         X         Y         Z novo_index
index
A      0.722126 -0.024349 -0.495746 -0.455249         CA
B      1.278790  0.928622  0.648145 -0.137351         NY
C      2.397857 -1.606492 -0.809873 -0.859328         OR
D     -2.061293 -0.770464 -0.753148  1.179107         CO
E      0.747019  2.836140 -1.211252  0.727634         WY

In [ ]:
df.reset_index().set_index('novo_index')
# bota o novo índice no lugar do antigo

           index         W         X         Y         Z
novo_index
CA             A  0.722126 -0.024349 -0.495746 -0.455249
NY             B  1.278790  0.928622  0.648145 -0.137351
OR             C  2.397857 -1.606492 -0.809873 -0.859328
CO             D -2.061293 -0.770464 -0.753148  1.179107
WY             E  0.747019  2.836140 -1.211252  0.727634

### Hierarquia de índices e índices múltiplos

In [ ]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1, 2, 3, 1, 2, 3]

hier_index = list(zip(outside, inside))
# zip encaixa duas listas e retorna uma tupla

In [51]:
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [52]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [53]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [ ]:
df = pd.DataFrame(np.random.randn(6, 2), index = hier_index, columns=['A', 'B'])
# faz duas partes de índice 
# é útil para fazer separações, tipo: homem e mulher
# é raro de se utilizar

In [55]:
df

             B         B
G1 1 -2.023363 -1.949194
   2 -1.101643  1.116874
   3 -1.288808 -0.851931
G2 1 -1.748355  1.238774
   2  0.241785 -0.190667
   3  0.508236  1.970840

In [ ]:
df.loc['G1'].loc[1]
# para pegar o index numerico é necessário pegar a parte

B   -2.023363
B   -1.949194
Name: 1, dtype: float64

In [58]:
df.index.names = ['Grupo', 'Número']

In [59]:
df

                     B         B
Grupo Número
G1    1      -2.023363 -1.949194
      2      -1.101643  1.116874
      3      -1.288808 -0.851931
G2    1      -1.748355  1.238774
      2       0.241785 -0.190667
      3       0.508236  1.970840

In [ ]:
df.xs(1, level = 'Número')
# pega o índice 1 das duas partes

              B         B
Grupo
G1    -2.023363 -1.949194
G2    -1.748355  1.238774

In [83]:
informacoes = {'NOTA1': [10, 4, 7, 9], 'NOTA2': [5, 6, 9, 9], 'NOTA3': [8, 8, 9, 3]}

nomes = 'yuri nayra braga hila'.split( )

df = pd.DataFrame(informacoes, index= nomes)
df['media'] = (((df['NOTA1'] + df['NOTA2']) * 2 + df['NOTA3']) / 5)
df['aprovado'] =  df['media'] > 7

In [84]:
df

       NOTA1  NOTA2  NOTA3  media  aprovado
yuri      10      5      8    7.6      True
nayra      4      6      8    5.6     False
braga      7      9      9    8.2      True
hila       9      9      3    7.8      True

### Manipulação de dados ausentes:

In [85]:
df = pd.DataFrame({
    'A' : [1, 2, np.nan],
    'B' : [5, np.nan, np.nan],
    'C' : [1, 2, 3]
})

In [86]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna()
# joga fora o índice 1 e 2, pois possui índices vazios
# drop NaN

     A    B  C
0  1.0  5.0  1

In [ ]:
df.dropna(axis = 1)
# joga fora a coluna A e B
# pois possui NaN

   C
0  1
1  2
2  3

In [ ]:
df.dropna(axis = 1, thresh = 2 )
# threh =  tolerância, nesse caso 1 NaN

     A  C
0  1.0  1
1  2.0  2
2  NaN  3

In [93]:
df.fillna(0)
# altera o valor dos NaN
# pode ser número ou string

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [ ]:
df['A'].mean()
# faz a média da Series

np.float64(1.5)

In [ ]:
df['A'].sum()
# soma a Series

np.float64(3.0)

In [ ]:
df['A'].fillna(value = df['A'].mean())
# preenche o NaN com a média dos valores da Series A

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [ ]:
df.ffill()
# preenche com o último número da coluna

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

### GroupBy:

In [122]:
data = {
    'Classe': ['Júnior', 'Júnior', 'Pleno', 'Pleno', 'Sênior', 'Sênior'],
    'Nome' : ['Jorge', 'Carlos', 'Roberta', 'Patricia', 'Bruno', 'Vera'],
    'Venda' : [200, 120, 340, 124, 243, 350]
}

In [123]:
df = pd.DataFrame(data)

In [103]:
df

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patricia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350

In [106]:
group = df.groupby('Classe')
# guarde drupo em uma variável
# agrupa por classe
# tipo uma sanfona, agrupa dps expande

In [ ]:
group.sum(numeric_only=True)
# para aparecer apenas os números mude o numeric_only para True

        Venda
Classe
Júnior    320
Pleno     464
Sênior    593

In [112]:
group.mean(numeric_only=True)

        Venda
Classe
Júnior  160.0
Pleno   232.0
Sênior  296.5

In [113]:
df.groupby('Classe').min()

            Nome  Venda
Classe
Júnior    Carlos    120
Pleno   Patricia    124
Sênior     Bruno    243

In [114]:
df.groupby('Classe').max()

           Nome  Venda
Classe
Júnior    Jorge    200
Pleno   Roberta    340
Sênior     Vera    350

In [125]:
# df2 = df
# se criar dessa forma dá erro, pois o python cria um ponteiro entre as duas, o correto é utilizar .copy()
df2 = df.copy()

In [126]:
df2['Venda'] = [150, 432, 190, 230, 410,155]

In [127]:
df

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patricia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350

In [128]:
df2

   Classe      Nome  Venda
0  Júnior     Jorge    150
1  Júnior    Carlos    432
2   Pleno   Roberta    190
3   Pleno  Patricia    230
4  Sênior     Bruno    410
5  Sênior      Vera    155

In [130]:
df3 = pd.concat([df, df2])
# concatena os DataFrames

In [131]:
df3

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patricia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350
0  Júnior     Jorge    150
1  Júnior    Carlos    432
2   Pleno   Roberta    190
3   Pleno  Patricia    230
4  Sênior     Bruno    410
5  Sênior      Vera    155

In [ ]:
df3.groupby(['Classe', 'Nome']).sum()
# da para ocupar mais de um elemento

                 Venda
Classe Nome
Júnior Carlos      552
       Jorge       350
Pleno  Patricia    354
       Roberta     530
Sênior Bruno       653
       Vera        505